version: '3.0'
services:
  run:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    volumes:
      - /muni-sc/test/:/muni-sc/
    command: bash -c "python main.py
                              -o /muni-sc/organized_runs/
                              -w /muni-sc/wsi/
                              -d /muni-sc/Libraries"
