apiVersion: batch/v1
kind: CronJob
metadata:
  name: upload-sequencing
spec:
  schedule: "0 22 * * 0,3,5"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 1000
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            runAsUser: 1005
            runAsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
          containers:
          - name: organise-sequencing
            image: tomashoufek/data-catalogue-uploader:1.0.1
            imagePullPolicy: Always
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
            env:
              - name: CATALOG_LOGIN
                valueFrom:
                  secretKeyRef:
                    name: catalog-secret
                    key: username
              - name: CATALOG_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: catalog-secret
                    key: password
              - name: HTTPS_PROXY
                valueFrom:
                  secretKeyRef:
                    name: catalog-secret
                    key: httpsproxy
            command: ["python", "main.py", "-o", "/data/OrganisedRuns/", "-w", "/wsi/", "-d", "/data/Libraries/"]
            volumeMounts:
            - name: storage-catalogue-volume
              mountPath: /data/
            - name: data-wsi-volume
              mountPath: /wsi/
              subPath: tiff
          restartPolicy: "Never"
          volumes:
          - name: storage-catalogue-volume
            persistentVolumeClaim:
              claimName: pvc-storage-catalogue-secret
          - name: data-wsi-volume
            persistentVolumeClaim:
              claimName: pvc-osd-secret